name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew cleanBuildTestJacoco
      - uses: actions/upload-artifact@v2
        with:
          name: codestyle-jar
          path: build/libs/
      - uses: actions/upload-artifact@v2
        with:
          name: jacoco
          path: build/reports/jacoco/test/html/
      - uses: actions/upload-artifact@v2
        with:
          name: tests
          path: build/test-results/test/TEST-*.xml
